class AddressData {
  static const Map<String, List<String>> regionProvinces = {
    "Region I": ["Ilocos Norte", "Ilocos Sur", "La Union", "Pangasinan"],
    "Region II": ["Batanes", "Cagayan", "Isabela", "Nueva Vizcaya", "Quirino"],
    "Region III": ["Aurora", "Bataan", "Bulacan", "Nueva Ecija", "Pampanga", "Tarlac", "Zambales"],
    "Region IV-A": ["Batangas", "Cavite", "Laguna", "Quezon", "Rizal"],
    "Region IV-B": ["Marinduque", "Occidental Mindoro", "Oriental Mindoro", "Palawan", "Romblon"],
    "Region V": ["Albay", "Camarines Norte", "Camarines Sur", "Catanduanes", "Masbate", "Sorsogon"],
    "Region VI": ["Aklan", "Antique", "Capiz", "Guimaras", "Iloilo", "Negros Occidental"],
    "Region VII": ["Bohol", "Cebu", "Negros Oriental", "Siquijor"],
    "REGION VIII": ["Biliran", "Eastern Samar", "Leyte", "Northern Samar", "Samar", "Southern Leyte"],
    "REGION IX": ["Zamboanga del Norte", "Zamboanga del Sur", "Zamboanga Sibugay"],
    "REGION X": ["Bukidnon", "Camiguin", "Lanao del Norte", "Misamis Occidental", "Misamis Oriental"],
    "REGION XI": ["Davao de Oro", "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental"],
    "REGION XII": ["Cotabato", "Sarangani", "South Cotabato", "Sultan Kudarat"],
    "REGION XIII": ["Agusan del Norte", "Agusan del Sur", "Dinagat Islands", "Surigao del Norte", "Surigao del Sur"],
  };

  static const Map<String, List<String>> provinceCities = {
    // BATANGAS
    "Batangas": ["Batangas City", "Lipa", "Tanauan", "Agoncillo", "Alitagtag", "Balayan", "Balete", "Bauan", "Calaca", "Calatagan", "Cuenca", "Ibaan", "Laurel", "Lemery", "Lian", "Lobo", "Mabini", "Malvar", "Mataasnakahoy", "Nasugbu", "Padre Garcia", "Rosario", "San Jose", "San Juan", "San Luis", "San Nicolas", "San Pascual", "Santa Teresita", "Santo Tomas", "Taal", "Talisay", "Taysan", "Tingloy", "Tuy"],
    // CAVITE
    "Cavite": ["Bacoor", "Cavite City", "Dasmariñas", "General Trias", "Imus", "Tagaytay", "Trece Martires", "Alfonso", "Amadeo", "Carmona", "General Emilio Aguinaldo", "Indang", "Kawit", "Magallanes", "Maragondon", "Mendez", "Naic", "Noveleta", "Rosario", "Silang", "Tanza", "Ternate"],
    // LAGUNA
    "Laguna": ["Biñan", "Cabuyao", "Calamba", "San Pablo", "San Pedro", "Santa Rosa", "Alaminos", "Bay", "Calauan", "Cavinti", "Famy", "Kalayaan", "Liliw", "Los Baños", "Luisiana", "Lumban", "Mabitac", "Magdalena", "Majayjay", "Nagcarlan", "Paete", "Pagsanjan", "Pakil", "Pangil", "Pila", "Rizal", "Santa Cruz", "Santa Maria", "Siniloan", "Victoria"],
    // RIZAL
    "Rizal": ["Antipolo", "Angono", "Baras", "Binangonan", "Cainta", "Cardona", "Jalajala", "Morong", "Pililla", "Rodriguez", "San Mateo", "Tanay", "Taytay", "Teresa"],
    // QUEZON
    "Quezon": ["Lucena", "Tayabas", "Agdangan", "Alabat", "Atimonan", "Buenavista", "Burdeos", "Calauag", "Candelaria", "Catanauan", "Dolores", "General Luna", "General Nakar", "Guinayangan", "Gumaca", "Infanta", "Jomalig", "Lopez", "Lucban", "Macalelon", "Mauban", "Mulanay", "Padre Burgos", "Pagbilao", "Panukulan", "Patnanungan", "Perez", "Pitogo", "Plaridel", "Polillo", "Quezon", "Real", "Sampaloc", "San Andres", "San Antonio", "San Francisco", "San Narciso", "Sariaya", "Tagkawayan", "Tiaong", "Unisan"],
    // OTHER REGIONS MENTIONED
    "Ilocos Norte": ["Laoag", "Batac", "Pagudpud", "Paoay", "Bangui"],
    "Ilocos Sur": ["Vigan", "Candon", "Bantay", "Narvacan"],
    "La Union": ["San Fernando", "Agoo", "Bauang", "San Juan"],
    "Pangasinan": ["Dagupan", "Alaminos", "Urdaneta", "Lingayen", "Calasiao", "Mangaldan"],
    "Bataan": ["Balanga", "Mariveles", "Dinalupihan", "Orani"],
    "Bulacan": ["Malolos", "Meycauayan", "San Jose del Monte", "Baliuag", "Bocaue", "Plaridel"],
    "Nueva Ecija": ["Cabanatuan", "Gapan", "Palayan", "San Jose", "Science City of Muñoz"],
    "Pampanga": ["Angeles", "San Fernando", "Mabalacat", "Arayat", "Guagua", "Porac"],
    "Tarlac": ["Tarlac City", "Capas", "Concepcion", "Paniqui"],
    "Zambales": ["Olongapo", "Iba", "Subic", "Castillejos"]
  };

  static const Map<String, List<String>> cityBarangays = {
    // =========================== CAVITE BARANGAYS ===========================
    "Bacoor": ["Alima","Aniban I","Aniban II","Aniban III","Aniban IV","Aniban V","Banalo","Bayanan","Digman","Dulong Bayan","Habay I","Habay II","Kaingin","Ligas I","Ligas II","Mabolo I","Mabolo II","Mabolo III","Maliksi I","Maliksi II","Maliksi III","Mambog I","Mambog II","Mambog III","Mambog IV","Mambog V","Molino I","Molino II","Molino III","Molino IV","Molino V","Molino VI","Molino VII","Niog I","Niog II","Niog III","Panapaan I","Panapaan II","Panapaan III","Panapaan IV","Panapaan V","Panapaan VI","Panapaan VII","Panapaan VIII","Real I","Real II","Salinas I","Salinas II","Sineguelasan","Tabing Dagat","Talaba I","Talaba II","Talaba III","Talaba IV","Talaba V","Talaba VI","Talaba VII","Zapote I","Zapote II","Zapote III","Zapote IV","Zapote V"],
    "Dasmariñas": ["Burol","Burol I","Burol II","Burol III","Datu Esmael","Emmanuelle Bergado I","Emmanuelle Bergado II","Fatima I","Fatima II","Fatima III","Langkaan I","Langkaan II","Luzviminda I","Luzviminda II","Luzviminda III","Paliparan I","Paliparan II","Paliparan III","Sabang","Salawag","Salitran I","Salitran II","Salitran III","Salitran IV","Sampaloc I","Sampaloc II","Sampaloc III","Sampaloc IV","Sampaloc V","San Agustin I","San Agustin II","San Agustin III","San Andres I","San Andres II","San Dionisio","San Esteban","San Francisco I","San Francisco II","San Isidro Labrador I","San Isidro Labrador II","San Jose","San Juan I","San Juan II","San Lorenzo Ruiz I","San Lorenzo Ruiz II","San Luis I","San Luis II","San Manuel I","San Manuel II","San Mateo","San Miguel","San Nicolas I","San Nicolas II","San Roque","San Simon","Santa Cristina I","Santa Cristina II","Santa Fe","Santa Lucia","Santa Maria","Santo Cristo","Santo Niño I","Santo Niño II","Victoria Reyes","Zone I","Zone II","Zone III","Zone IV"],
    "Imus": ["Alapan I-A","Alapan I-B","Alapan I-C","Alapan II-A","Alapan II-B","Anabu I-A","Anabu I-B","Anabu I-C","Anabu I-D","Anabu I-E","Anabu I-F","Anabu II-A","Anabu II-B","Anabu II-C","Anabu II-D","Bayan Luma I","Bayan Luma II","Bayan Luma III","Bayan Luma IV","Bayan Luma V","Bayan Luma VI","Bayan Luma VII","Bayan Luma VIII","Bayan Luma IX","Buhay na Tubig","Carsadang Bago I","Carsadang Bago II","Malagasang I-A","Malagasang I-B","Malagasang I-C","Malagasang I-D","Malagasang I-E","Malagasang I-F","Malagasang II-A","Malagasang II-B","Medicion I-A","Medicion I-B","Medicion II-A","Medicion II-B","Medicion II-C","Toclong I-A","Toclong I-B","Toclong I-C","Toclong II-A","Toclong II-B"],
    "General Trias": ["Bagumbayan","Biclatan","Buenavista I","Buenavista II","Buenavista III","Corregidor","Dulong Bayan","Governor Ferrer","Javalera","Manggahan","Navarro","Panungyanan","Pasong Camachile I","Pasong Camachile II","Pasong Kawayan I","Pasong Kawayan II","San Francisco","San Gabriel","San Juan I","San Juan II","San Jose","San Nicolas","San Pedro","San Rafael","Santa Clara"],
    "Trece Martires": ["Aguado","Cabezas","Cabuco","Conchu","De Ocampo","Gregorio","Hugo Perez","Inocencio","Lapidario","Luciano","Osorio","Perez","San Agustin"],
    "Tagaytay": ["Asisan","Bagong Tubig","Calabuso","Dapdap East","Dapdap West","Francisco","Guinhawa North","Guinhawa South","Iruhin Central","Iruhin East","Iruhin South","Iruhin West","Kaybagal Central","Kaybagal East","Kaybagal North","Kaybagal South","Mag-Asawang Ilat","Maharlika East","Maharlika West","Maitim 2nd Central","Maitim 2nd East","Maitim 2nd West","Mendez Crossing East","Mendez Crossing West","Neogan","Patutong Malaki North","Patutong Malaki South","San Jose","Silang Crossing East","Silang Crossing West","Sungay East","Sungay West","Tolentino East","Tolentino West","Zambal"],
    "Cavite City": ["Barangay 1","Barangay 2","Barangay 3","Barangay 4","Barangay 5","Barangay 6","Barangay 7","Barangay 8","Barangay 9","Barangay 10","Barangay 10-A","Barangay 10-B","Barangay 11","Barangay 12","Barangay 13","Barangay 14","Barangay 15","Barangay 16","Barangay 17","Barangay 18","Barangay 19","Barangay 20","Barangay 21","Barangay 22","Barangay 22-A","Barangay 23","Barangay 24","Barangay 25","Barangay 26","Barangay 27","Barangay 28","Barangay 29","Barangay 29-A","Barangay 30","Barangay 31","Barangay 32","Barangay 33","Barangay 34","Barangay 35","Barangay 36","Barangay 36-A","Barangay 37","Barangay 38","Barangay 39","Barangay 40","Barangay 41","Barangay 42","Barangay 42-A","Barangay 42-B","Barangay 42-C","Barangay 43","Barangay 44","Barangay 45","Barangay 46","Barangay 47","Barangay 47-A","Barangay 48","Barangay 49","Barangay 50","Barangay 51","Barangay 52","Barangay 53","Barangay 53-A","Barangay 53-B","Barangay 54","Barangay 54-A","Barangay 55","Barangay 56","Barangay 57","Barangay 58","Barangay 58-A","Barangay 59","Barangay 60","Barangay 61","Barangay 61-A","Barangay 62","Barangay 62-A","Barangay 62-B"],
    "Alfonso": ["Amuyong", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Bilog", "Buck Estate", "Esperanza Ibaba", "Esperanza Ilaya", "Kaysuyo", "Kaytitinga I", "Kaytitinga II", "Kaytitinga III", "Lucsuhin", "Lucsuhin Ilaya", "Mangas I", "Mangas II", "Marahan I", "Marahan II", "Matagbak I", "Matagbak II", "Pajo", "Palumlum", "Santa Teresa", "Sikat", "Sinaite", "Sulsugin", "Taywanak Ibaba", "Taywanak Ilaya", "Upli", "Mabuhay"],
    "Amadeo": ["Banaybanay", "Bucal", "Dagatan", "Halang", "Loma", "Maitim I", "Maymangga", "Minantok East", "Minantok West", "Pangil", "Barangay I", "Barangay II", "Barangay III", "Barangay IV", "Barangay V", "Barangay VI", "Barangay VII", "Barangay VIII", "Barangay IX", "Barangay X", "Barangay XI", "Barangay XII", "Salaban", "Talon"],
    "Carmona": ["Bancal", "Cabilang Baybay", "Carmona Estates", "Lantic", "Mabuhay", "Maduya", "Milagrosa", "Barangay 1", "Barangay 2", "Barangay 3", "Barangay 4", "Barangay 5", "Barangay 6", "Barangay 7", "Barangay 8"],
    "General Emilio Aguinaldo": ["A. Dalusag", "Batangas II", "Biga", "Castanos Cerca", "Castanos Lejos", "Kabulusan", "Kaymisas", "Kaypaet", "Lumipa", "Narvaez", "Poblacion I", "Poblacion II", "Poblacion III", "Poblacion IV", "Tabora"],
    "Indang": ["Agus-us", "Alulod", "Banaba Cerca", "Banaba Lejos", "Bancod", "Buna Cerca", "Buna Lejos I", "Buna Lejos II", "Calumpang Cerca", "Calumpang Lejos I", "Carasuchi", "Daine I", "Daine II", "Guyam Malaki", "Guyam Munti", "Harasan", "Kayquit I", "Kayquit II", "Kayquit III", "Kaytambog", "Kaytitinga I", "Kaytitinga II", "Kaytitinga III", "Lucsuhin", "Lucsuhin Ilaya", "Lumampong Balagbag", "Lumampong Halayhay", "Mahabang Kahoy Cerca", "Mahabang Kahoy Lejos", "Mataas Na Lupa", "Poblacion 1", "Poblacion 2", "Poblacion 3", "Poblacion 4", "Pulo", "Tambo Balagbag", "Tambo Ilaya", "Tambo Kulit", "Tambo Malaki"],
    "Kawit": ["Balsahan-Bisita", "Batong Dalig", "Binakayan-Aplaya", "Binakayan-Kanluran", "Congbalay-Legaspi", "Gahak", "Kaingen", "Manggahan-Lawin", "Marulas", "Panamitan", "Poblacion", "Magdalo", "San Sebastian", "Santa Isabel", "Tabon I", "Tabon II", "Tabon III", "Toclong", "Tramo-Bantayan", "Wakakas"],
    "Magallanes": ["Baliis", "Bendita I", "Bendita II", "Caluangan", "Cabulusan", "Medina", "Pacheco", "Poblacion 1", "Poblacion 2", "Poblacion 3", "Poblacion 4", "Poblacion 5", "Ramirez", "San Agustin", "Tua", "Urdaneta"],
    "Maragondon": ["Bucal I", "Bucal II", "Bucal III", "Bucal IV", "Caingin Poblacion", "Garita I A", "Garita I B", "Layong Mabilog", "Mabato", "Pantihan I", "Pantihan II", "Pantihan III", "Pantihan IV", "Pinagsanhan A", "Pinagsanhan B", "Poblacion I A", "Poblacion I B", "Poblacion II A", "Poblacion II B", "San Miguel A", "San Miguel B", "Talipusngo", "Tulay Silangan", "Tulay Kanluran"],
    "Mendez": ["Anuling Cerca I", "Anuling Cerca II", "Anuling Lejos I", "Anuling Lejos II", "Asis I", "Asis II", "Asis III", "Banayad", "Bukal", "Galicia I", "Galicia II", "Galicia III", "Miguel Mojica", "Palocpoc I", "Palocpoc II", "Panungyan I", "Panungyan II", "Poblacion I", "Poblacion II", "Poblacion III", "Poblacion IV", "Poblacion V", "Poblacion VI", "Poblacion VII"],
    "Naic": ["Bagong Kalsada", "Balsahan", "Bancaan", "Bucana Malaki", "Bucana Sasahan", "Captain C. Nazareno", "Calubcob", "Gomez-Zamora", "Halang", "Humbac", "Ibayo Estacion", "Ibayo Silangan", "Kanluran", "Labac", "Latoria", "Mabolo", "Makina", "Malainen Bago", "Malainen Luma", "Molino", "Munting Mapino", "Muzon", "Palangue 1", "Palangue 2", "Palangue 3", "Sabang", "San Roque", "Santulan", "Sapa", "Timalan Balsahan", "Timalan Concepcion"],
    "Noveleta": ["Magdiwang", "Poblacion", "Salcedo I", "Salcedo II", "San Antonio I", "San Antonio II", "San Jose I", "San Jose II", "San Juan 1", "San Juan 2", "San Rafael 1", "San Rafael 2", "San Rafael 3", "San Rafael 4", "Santa Rosa 1", "Santa Rosa 2"],
    "Rosario": ["Bagbag I", "Bagbag II", "Kanluran", "Ligtong I", "Ligtong II", "Ligtong III", "Ligtong IV", "Muzon I", "Muzon II", "Poblacion", "Sapa I", "Sapa II", "Sapa III", "Sapa IV", "Silangan I", "Silangan II", "Tejeros Convention", "Wawa I", "Wawa II", "Wawa III"],
    "Silang": ["Acacia", "Adlas", "Anahaw 1", "Anahaw 2", "Balite 1", "Balite 2", "Biga 1", "Biga 2", "Biluso", "Bucal", "Buho", "Bulihan", "Cabangaan", "Carmen", "Hoyo", "Hukay", "Iba", "Inchican", "Kalubkob", "Kaong", "Lalaan 1", "Lalaan 2", "Litlit", "Lucsuhin", "Lumil", "Maguyam", "Malabag", "Mataas Na Burol", "Munting Ilog", "Paligawan", "Pasong Langka", "Pooc 1", "Pooc 2", "Puting Kahoy", "Sabutan", "San Miguel 1", "San Miguel 2", "San Vicente 1", "San Vicente 2", "Santol", "Tartaria", "Tibig", "Toledo", "Tubuan 1", "Tubuan 2", "Tubuan 3", "Ulat"],
    "Tanza": ["A. Bonifacio", "Amaya I", "Amaya II", "Amaya III", "Amaya IV", "Amaya V", "Amaya VI", "Amaya VII", "Bagtas", "Biga", "Biwas", "Bucal", "Bunga", "Capipisa", "Daang Amaya I", "Daang Amaya II", "Daang Amaya III", "Halayhay", "Julugan I", "Julugan II", "Julugan III", "Julugan IV", "Julugan V", "Julugan VI", "Julugan VII", "Julugan VIII", "Lambingan", "Mulawin", "Paradahan I", "Paradahan II", "Poblacion I", "Poblacion II", "Poblacion III", "Poblacion IV", "Punta I", "Punta II", "Sahud Ulan", "Sanja Mayor", "Santol", "Tres Cruses"],
    "Ternate": ["Bucana", "Poblacion I", "Poblacion II", "Poblacion III", "San Jose", "San Juan I", "San Juan II", "Sapang I", "Sapang II"]
  };
}
